config/routes.rb
DataTracker::Application.routes.draw do
  resources :census_table_formats
  resources :census_formats
  resources :scout_types
  resources :membership_types
  resources :award_types
  resources :memberships
  resources :years
  resources :organisation_types

  resources :awards do
    collection { post :import}
    collection { get :upload}
  end

  resources :organisations do
    collection { post :import}
    collection { get :upload}
  end

  match '/reports/:action/:organisation_id' => 'reports#:action'
  match '/reports/:action' => 'reports#:action'

  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :users

  root :to => "home#index"
end

app/models/award.rb
class Award < ActiveRecord::Base
  require 'csv'
  
  belongs_to :organisation
  belongs_to :year
  belongs_to :award_type
  belongs_to :scout_type
  attr_accessible :organisation, :organisation_id, :year, :year_id, :award_type, :award_type_id, :award_count, :scout_type, :scout_type_id

  validates_presence_of :organisation, :year, :award_type, :scout_type

  def self.import(file)
    unless file.nil?
      CSV.foreach(file.path, headers: true) do |row|
        record = row.to_hash
        organisation = Organisation.find_by_registration_no(record["organisation"])
        year = Year.find_by_name(record["year"])
        award_type = AwardType.find_by_name(record["award_type"])
        scout_type = ScoutType.find_by_name(record["scout_type"])
        award_count = record["award_count"]
        Award.create(
          organisation: organisation, 
          year: year, 
          award_type: award_type, 
          scout_type: scout_type, 
          award_count: award_count)
      end
    end
  end

end

app/models/award_type.rb
class AwardType < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  load_and_authorize_resource
  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = Award.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render json: @award, status: :created, location: @award }
      else
        format.html { render action: "new" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to awards_url }
      format.json { head :no_content }
    end
  end

  def upload
  end

  def import
    Award.import(params[:file])
    redirect_to awards_url, notice: "Awards Imported"
  end
end

app/views/awards/_form.html.erb
<%= simple_form_for @award, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.association :organisation, collection: Organisation.all(order: 'name'), value_method: :id, label_method: :name, include_blank: false %>
  <%= f.association :year, collection: Year.all(order: 'name'), value_method: :id, label_method: :name, include_blank: false %>
  <%= f.association :award_type, collection: AwardType.all(order: 'name'), value_method: :id, label_method: :name, include_blank: false %>
  <%= f.association :scout_type, collection: ScoutType.all(order: 'name'), value_method: :id, label_method: :name, include_blank: false %>
  <%= f.input :award_count %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                awards_path, :class => 'btn' %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<%- model_class = Award -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/awards/index.html.erb
<%- model_class = Award -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_award_path,
            :class => 'btn btn-primary' %>

<%= link_to t('.upload', :default => t("helpers.links.upload")),
upload_awards_path,
:class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:organisation_id) %></th>
      <th><%= model_class.human_attribute_name(:year_id) %></th>
      <th><%= model_class.human_attribute_name(:award_type_id) %></th>
      <th><%= model_class.human_attribute_name(:scout_type_id) %></th>
      <th><%= model_class.human_attribute_name(:award_count) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @awards.each do |award| %>
      <tr id=<%= award.id %>>
        <td><%= link_to award.organisation.name, organisation_path(award.organisation) %></td>
        <td><%= award.year.name%></td>
        <td><%= award.award_type.name %></td>
        <td><%= award.scout_type.name %></td>
        <td><%= award.award_count %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_award_path(award), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      award_path(award),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/awards/new.html.erb
<%- model_class = Award -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/awards/show.html.erb
<%- model_class = Award -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:organisation_id) %>:</strong></dt>
  <dd><%= @award.organisation_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year_id) %>:</strong></dt>
  <dd><%= @award.year_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:award_type_id) %>:</strong></dt>
  <dd><%= @award.award_type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scout_type_id) %>:</strong></dt>
  <dd><%= @award.scout_type_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              awards_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_award_path(@award), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              award_path(@award),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/awards/upload.html.erb
<%- model_class = Award -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "#{model_class.model_name.human} Import") %></h1>
</div>

<%= form_tag import_awards_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import", :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            awards_path, :class => 'btn' %>
<% end %>