config/routes.rb
DataTracker::Application.routes.draw do
  resources :census_table_formats
  resources :census_formats
  resources :scout_types
  resources :membership_types
  resources :award_types
  resources :memberships
  resources :years
  resources :organisation_types

  resources :awards do
    collection { post :import}
    collection { get :upload}
  end

  resources :organisations do
    collection { post :import}
    collection { get :upload}
  end

  match '/reports/:action/:organisation_id' => 'reports#:action'
  match '/reports/:action' => 'reports#:action'

  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :users

  root :to => "home#index"
end

app/controllers/scout_types_controller.rb
class ScoutTypesController < ApplicationController
  # GET /scout_types
  # GET /scout_types.json
  def index
    @scout_types = ScoutType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scout_types }
    end
  end

  # GET /scout_types/1
  # GET /scout_types/1.json
  def show
    @scout_type = ScoutType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scout_type }
    end
  end

  # GET /scout_types/new
  # GET /scout_types/new.json
  def new
    @scout_type = ScoutType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scout_type }
    end
  end

  # GET /scout_types/1/edit
  def edit
    @scout_type = ScoutType.find(params[:id])
  end

  # POST /scout_types
  # POST /scout_types.json
  def create
    @scout_type = ScoutType.new(params[:scout_type])

    respond_to do |format|
      if @scout_type.save
        format.html { redirect_to @scout_type, notice: 'Scout type was successfully created.' }
        format.json { render json: @scout_type, status: :created, location: @scout_type }
      else
        format.html { render action: "new" }
        format.json { render json: @scout_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scout_types/1
  # PUT /scout_types/1.json
  def update
    @scout_type = ScoutType.find(params[:id])

    respond_to do |format|
      if @scout_type.update_attributes(params[:scout_type])
        format.html { redirect_to @scout_type, notice: 'Scout type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scout_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scout_types/1
  # DELETE /scout_types/1.json
  def destroy
    @scout_type = ScoutType.find(params[:id])
    @scout_type.destroy

    respond_to do |format|
      format.html { redirect_to scout_types_url }
      format.json { head :no_content }
    end
  end
end

app/views/scout_types/_form.html.erb
<%= simple_form_for @scout_type, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                scout_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/scout_types/edit.html.erb
<%- model_class = ScoutType -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/scout_types/index.html.erb
<%- model_class = ScoutType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @scout_types.each do |scout_type| %>
      <tr id=<%= scout_type.id %>>
        <td><%= link_to scout_type.name, scout_type_path(scout_type) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_scout_type_path(scout_type), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      scout_type_path(scout_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_scout_type_path,
            :class => 'btn btn-primary' %>

app/views/scout_types/new.html.erb
<%- model_class = ScoutType -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/scout_types/show.html.erb
<%- model_class = ScoutType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @scout_type.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              scout_types_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_scout_type_path(@scout_type), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              scout_type_path(@scout_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>