config/routes.rb
DataTracker::Application.routes.draw do
  resources :census_table_formats
  resources :census_formats
  resources :scout_types
  resources :membership_types
  resources :award_types
  resources :memberships
  resources :years
  resources :organisation_types

  resources :awards do
    collection { post :import}
    collection { get :upload}
  end

  resources :organisations do
    collection { post :import}
    collection { get :upload}
  end

  match '/reports/:action/:organisation_id' => 'reports#:action'
  match '/reports/:action' => 'reports#:action'

  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :users

  root :to => "home#index"
end

app/models/census_format.rb
class CensusFormat < ActiveRecord::Base
  has_many :census_table_formats, :class_name => "CensusTableFormat"
  attr_accessible :name, :table_xpath
  validates_presence_of :name, :table_xpath
end

app/controllers/census_formats_controller.rb
class CensusFormatsController < ApplicationController
  # GET /census_formats
  # GET /census_formats.json
  def index
    @census_formats = CensusFormat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @census_formats }
    end
  end

  # GET /census_formats/1
  # GET /census_formats/1.json
  def show
    @census_format = CensusFormat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @census_format }
    end
  end

  # GET /census_formats/new
  # GET /census_formats/new.json
  def new
    @census_format = CensusFormat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @census_format }
    end
  end

  # GET /census_formats/1/edit
  def edit
    @census_format = CensusFormat.find(params[:id])
  end

  # POST /census_formats
  # POST /census_formats.json
  def create
    @census_format = CensusFormat.new(params[:census_format])

    respond_to do |format|
      if @census_format.save
        format.html { redirect_to @census_format, notice: 'Census format was successfully created.' }
        format.json { render json: @census_format, status: :created, location: @census_format }
      else
        format.html { render action: "new" }
        format.json { render json: @census_format.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /census_formats/1
  # PUT /census_formats/1.json
  def update
    @census_format = CensusFormat.find(params[:id])

    respond_to do |format|
      if @census_format.update_attributes(params[:census_format])
        format.html { redirect_to @census_format, notice: 'Census format was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @census_format.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /census_formats/1
  # DELETE /census_formats/1.json
  def destroy
    @census_format = CensusFormat.find(params[:id])
    @census_format.destroy

    respond_to do |format|
      format.html { redirect_to census_formats_url }
      format.json { head :no_content }
    end
  end
end

app/views/census_formats/_form.html.erb
<%= simple_form_for @census_format, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :table_xpath %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                census_formats_path, :class => 'btn' %>
  </div>
<% end %>

app/views/census_formats/edit.html.erb
<%- model_class = CensusFormat -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/census_formats/index.html.erb
<%- model_class = CensusFormat -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:table_xpath) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @census_formats.each do |census_format| %>
      <tr id=<%= census_format.id %>>
        <td><%= link_to census_format.name, census_format_path(census_format) %></td>
        <td><%= census_format.table_xpath %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_census_format_path(census_format), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      census_format_path(census_format),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_census_format_path,
            :class => 'btn btn-primary' %>

app/views/census_formats/new.html.erb
<%- model_class = CensusFormat -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/census_formats/show.html.erb
<%- model_class = CensusFormat -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @census_format.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:table_xpath) %>:</strong></dt>
  <dd><%= @census_format.table_xpath %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              census_formats_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_census_format_path(@census_format), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              census_format_path(@census_format),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>